theme = "PaperMod"
baseURL = "https://ranitmukherjee.github.io/"
title = "Ranit Mukherjee"
languageCode = "en-us"
defaultContentLanguage = "en"

[params]
  name = "Ranit Mukherjee"
  description = "Computer Science undergraduate, Open Source Contributor, focused on web and mobile development."
  location = "Kolkata, West Bengal, India"
  profile_image = "/images/profile.jpg"
  mainSections = ["posts"]

[params.social]
  github = "https://github.com/RanitMukherjee"
  linkedin = "https://linkedin.com/in/ranitmukherjee2003"
  email = "mailto:littleranit@gmail.com"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Experience"
    url = "/experience/"
    weight = 2

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3

  [[menu.main]]
    name = "Achievements"
    url = "/achievements/"
    weight = 4

  [[menu.main]]
    name = "Certifications"
    url = "/certifications/"
    weight = 5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true